name: color-free
on:
  push:
    branches: [ master ]
    paths:
    - 'src/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: yarn install && yarn build