name: color-free
on:
  push:
    branches: [ master ]
    paths:
    - 'src/**'
    - '.github/workflows/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'src/**'
    - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: yarn install && yarn build